"""
Node 7: Heatmap Report Generator

Responsibility:
- Generate a bubble chart PDF based on aggregated scores and code mappings.
"""

import os
import json
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import xml.sax.saxutils as saxutils
from datetime import datetime
from PIL import Image as PILImage

from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor

from src.utils import logger, audit_snapshot

def node_7_heatmap_report_generator(state):
    logger.info("=" * 60)
    logger.info("NODE 7: Heatmap Report Generator")
    logger.info("=" * 60)

    config = state.get("config", {})
    report_config = config.get("report_generation", {})
    analyze_class_level = report_config.get("analyze_class_level", False)

    output_folder = report_config.get("output_folder", "output")
    os.makedirs(output_folder, exist_ok=True)

    # Determine paths and output filename
    agg_path_config = report_config.get("aggregated_data_file_path", "")
    raw_path_config = report_config.get("code_mapping_file_path", "")

    suffix = "_heatmap_report_object_level.pdf" if analyze_class_level else "_heatmap_report.pdf"

    if agg_path_config and raw_path_config and os.path.exists(agg_path_config) and os.path.exists(raw_path_config):
        is_direct = True
        agg_path = agg_path_config
        raw_path = raw_path_config
        
        # Substring of the first 15 chars of aggregated_data_file_path filename
        base_name = os.path.basename(agg_path)
        prefix = base_name[:15]
        output_pdf_name = f"{prefix}{suffix}"
    else:
        # Get from state (generated by exporter)
        agg_path = state.get("report_aggregated_file", "")
        raw_path = state.get("report_raw_file", "")
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_pdf_name = f"{timestamp}{suffix}"

    output_pdf_path = os.path.join(output_folder, output_pdf_name)

    if not agg_path or not os.path.exists(agg_path) or not raw_path or not os.path.exists(raw_path):
        logger.error("Missing required data files for report generation.")
        return state

    logger.info("Generating heatmap report...")
    logger.info(f"Aggregated data: {agg_path}")
    logger.info(f"Raw data: {raw_path}")

    # 1. Load Data
    with open(agg_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    with open(raw_path, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    # 2. Extract analyzed timeframe and pull requests
    oldest_date = None
    newest_date = None
    for item in raw_data:
        # Dates for timeframe (use all commits to find the range of the raw data analyzed)
        commits = item.get("commits", [])
        for c in commits:
            c_date_str = c.get("commit_date")
            if c_date_str:
                try:
                    c_date = datetime.fromisoformat(c_date_str.replace("Z", "+00:00"))
                    if oldest_date is None or c_date < oldest_date:
                        oldest_date = c_date
                    if newest_date is None or c_date > newest_date:
                        newest_date = c_date
                except ValueError:
                    pass

    valid_commit_hashes = set()
    for proj in data:
        for cls in proj.get('classes', []):
            if cls.get('impact_score', 0) > 0:
                for c in cls.get('commit_contributions', []):
                    if c.get('impact_score', 0) > 0:
                        c_hash = c.get('commit_hash')
                        if c_hash:
                            valid_commit_hashes.add(c_hash)

    analyzed_pull_requests = len(valid_commit_hashes)
    timeframe_str = "N/A"
    if oldest_date and newest_date:
        timeframe_str = f"Dal {oldest_date.strftime('%Y-%m-%d')} al {newest_date.strftime('%Y-%m-%d')}"

    # 3. Extraction and filtering for the Bubble Chart
    records = []
    for proj in data:
        proj_name = proj.get('project_name')
        for cls in proj.get('classes', []):
            impact = cls.get('impact_score', 0)
            
            if impact > 0:
                records.append({
                    'Project': proj_name,
                    'Class': cls.get('class_name').split('.')[-1],
                    'FullName': cls.get('class_name'),
                    'ImpactScore': impact,
                    'LogicalObjectsCount': cls.get('logical_objects_count', 0),
                    'Commits': cls.get('commit_contributions', [])
                })

    df = pd.DataFrame(records)
    
    if df.empty:
        logger.warning("No classes with impact > 0 found. Report generation aborted.")
        return state

    # 4. Bubble Chart Generation
    project_max = df.groupby('Project')['ImpactScore'].max().reset_index()
    project_max = project_max.sort_values('ImpactScore', ascending=True) 
    ordered_projects = project_max['Project'].tolist()

    df['Project'] = pd.Categorical(df['Project'], categories=ordered_projects, ordered=True)

    fig_height = max(8, len(ordered_projects) * 0.4)
    plt.figure(figsize=(14, fig_height))

    sizes = np.clip(df['LogicalObjectsCount'] * 5, 50, 3000)

    scatter = plt.scatter(x=df['ImpactScore'], 
                          y=df['Project'], 
                          s=sizes,
                          c=df['ImpactScore'], 
                          cmap='YlOrRd', 
                          alpha=0.75, 
                          edgecolors='gray',
                          linewidth=0.8)

    plt.colorbar(scatter, label='Livello di Calore (Impact Score)')

    for i, row in df.iterrows():
        if row['ImpactScore'] > 0:
            plt.text(row['ImpactScore'] + 0.06, row['Project'], row['Class'], 
                     va='center', ha='left', fontsize=9, 
                     bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=1))

    if analyze_class_level:
        plt.title('Bubble Chart: Livello di Calore degli Oggetti Logici', fontsize=16, pad=20)
        plt.xlabel("Calore dell'Oggetto Logico (Impact Score)", fontsize=12)
        plt.ylabel('Classi', fontsize=12)
    else:
        plt.title('Bubble Chart: Livello di Calore delle Classi', fontsize=16, pad=20)
        plt.xlabel('Calore della Classe (Impact Score)', fontsize=12)
        plt.ylabel('Progetti', fontsize=12)
    plt.grid(axis='y', linestyle='--', alpha=0.4)
    plt.grid(axis='x', linestyle='--', alpha=0.2)
    plt.xlim(-0.2, df['ImpactScore'].max() + 0.8) 
    plt.tight_layout()
    
    chart_path = os.path.join(output_folder, 'temp_bubble_chart.png')
    plt.savefig(chart_path, dpi=150)
    plt.close()

    # 5. PDF Generation
    doc = SimpleDocTemplate(output_pdf_path, pagesize=A4, rightMargin=30, leftMargin=30, topMargin=30, bottomMargin=30)
    styles = getSampleStyleSheet()
    
    title_style = styles['Heading1']
    title_style.alignment = 1 
    h2_style = ParagraphStyle(name='Heading2Custom', parent=styles['Heading2'], textColor=HexColor('#2c3e50'), spaceBefore=15, spaceAfter=5)
    normal_style = styles['Normal']
    bullet_style = ParagraphStyle(name='Bullet', parent=styles['Normal'], leftIndent=20, spaceAfter=2)

    story = []

    # Page 1: Intro
    story.append(Paragraph("Report Analisi Hotspot del Codice", title_style))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph(f"<b>Timeframe Analizzato:</b> {timeframe_str}", normal_style))
    story.append(Paragraph(f"<b>Commit Analizzati (sopra soglia):</b> {analyzed_pull_requests}", normal_style))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("Questo report include le classi e i commit con un <b>Impact Score maggiore di zero</b>.", normal_style))
    story.append(Spacer(1, 0.2 * inch))

    # Fit image to A4
    with PILImage.open(chart_path) as pimg:
        img_w, img_h = pimg.size
        aspect = img_h / img_w
        pdf_img_w = 530
        pdf_img_h = pdf_img_w * aspect
        if pdf_img_h > 700:
            pdf_img_h = 700
            pdf_img_w = 700 / aspect

    story.append(RLImage(chart_path, width=pdf_img_w, height=pdf_img_h))
    story.append(PageBreak())

    # Page 2: Details
    if analyze_class_level:
        story.append(Paragraph("Dettaglio dei Commit per Oggetto Logico (Bubble)", styles['Heading1']))
    else:
        story.append(Paragraph("Dettaglio dei Commit per Classe (Bubble)", styles['Heading1']))
    story.append(Spacer(1, 0.1 * inch))

    df_sorted = df.sort_values(by='ImpactScore', ascending=False)

    for i, row in df_sorted.iterrows():
        commits = row['Commits']
        valid_commits = [c for c in commits if c.get('impact_score', 0) > 0]
        
        if not valid_commits:
            continue
        
        valid_commits = sorted(valid_commits, key=lambda x: x.get('impact_score', 0), reverse=True)
        
        class_title = f"{row['Project']} ➔ {row['FullName']} (Impatto Totale: {row['ImpactScore']:.2f})"
        story.append(Paragraph(saxutils.escape(class_title), h2_style))
        
        for c in valid_commits:
            score = c.get('impact_score', 0)
            desc = c.get('commit_description', 'N/A').replace('\n', ' ').strip()
            desc = saxutils.escape(desc)
            
            if score < 0.01:
                line = f"<b>[&lt;0.01]</b> {desc}"
            else:
                line = f"<b>[{score:.2f}]</b> {desc}"
                
            story.append(Paragraph(f"• {line}", bullet_style))
        
        story.append(Spacer(1, 0.1 * inch))

    doc.build(story)
    
    if os.path.exists(chart_path):
        os.remove(chart_path)
        
    logger.info(f"Report completed and saved as: {output_pdf_path}")
    
    audit_snapshot({"report_path": output_pdf_path, "analyzed_pull_requests": analyzed_pull_requests, "timeframe": timeframe_str}, "node_7_heatmap_report_generator", "Report Generation", config)

    return state
